### ISSUE TITLE
bug: dc checker: sleep interrupted error.

### ISSUE THREAD

**Issue by ZynthZoldyck** [norecha/pokubot#10]
what to do with this? its doing fine on my laptop using win 7 x64 bit, that bug is from my desktop using win7 32 bit.
![untitled](https://cloud.githubusercontent.com/assets/10362403/5939443/b634922a-a73e-11e4-9402-236d263a07c7.jpg)

**Comment by norecha** [comment]
I don't know how you have SNAPSHOT version but that is an old version. See the version number on top right. Latest one should say v1.0.0. Try with that one
