### ISSUE TITLE
Use Of Dark Barrack Troops (Minions)

### ISSUE THREAD

**Issue by edxz** [norecha/pokubot#17]
Hi norecha, 
can you add the feature to train troops from dark barracks ?
it will benefits a lot as it decrease training time by making the use of all barracks
especially for BAM (Barbarians, Archers, and minions) combinations

**Comment by norecha** [comment]
Reasonable request, I will add it in the future

**Comment by T1g3rs65** [comment]
also I think I should add this and u are probably working on it already. But could u add it were it can request and use clan castle troops?

**Comment by jacobdabanqa** [comment]
its added in the donation one. :) i dont know if it works as i havnt tested it but i have seen the option.
