### ISSUE TITLE
MInd helping ...

### ISSUE THREAD

**Issue by berryben97** [norecha/pokubot#18]
I went to boost my barracks and now the bot wont even work ... is it because i boosted my barracks ? please help

**Comment by norecha** [comment]
I'm aware of this issue. When you boost, if one of the buttons on barracks is missing, it can't find the train button. Can you send me a screenshot after you click on boosted barracks

**Comment by berryben97** [comment]
Sorry the boost was over already ... But the bot worked again after the
boost was over ... But I can remember it wrote that it couldn't find the
barracks ... Sorry I didn't took a photo of it before the boost was over

**Comment by berryben97** [comment]
Hey is there any new update about the new feature background ?

**Comment by norecha** [comment]
I'm planning to have a paid version with more advanced features. It will be part of that, I'm not sure if I will add to free version

**Comment by berryben97** [comment]
Why make a paid version 😔😔 I love your work ...
