### ISSUE TITLE
just got this message

### ISSUE THREAD

**Issue by apyapy** [norecha/pokubot#25]
![toolong](https://cloud.githubusercontent.com/assets/10819281/6021068/5d551626-abbb-11e4-9fc0-a4fd59322dde.jpg)

any idea?

**Comment by norecha** [comment]
it is exactly what it says. you can't play for more than 6 hours. Wait 5 min. Bot should keep trying to log you back in

**Comment by apyapy** [comment]
thanks. reading online came up with this being a forced 5 min break. i hope the bot will keep logging me in for 5 mins and that having too much long sessions wont get anyone banned
