### ISSUE TITLE
boosting troops bug

### ISSUE THREAD

**Issue by alean753** [norecha/pokubot#29]
Bot doesn't work when barracks are boosted. Maybe you can put a box where we can choose if barracks are boosted or not. And thanks for the bot working fine without the boost keep up the good work.

**Comment by norecha** [comment]
Yeah I know this. For now you can just boost the other barracks and not boost first one. It assumes boost and boost all buttons are there

**Comment by alean753** [comment]
Oh ok sorry. Never thought about that. Thanks

**Comment by peintrain** [comment]
hi norecha!! can you add the dark barracks? and also a donate and request can you add those? THANKS
