### ISSUE TITLE
StateIdle

### ISSUE THREAD

**Issue by DougBrazil** [norecha/pokubot#32]
![stateidle](https://cloud.githubusercontent.com/assets/10978757/6170426/d8c9fb08-b2bb-11e4-998c-f6fc70b50744.jpg)
Hey,

I have set up everything but it keeps returning stateidle error.
(*For the screen resolution I had to fix it manually because the automatic resolution always was offcenter*)
(*Ive seen previous problems with this errors so I disabled my antivirus and the problem still remains*)
(*Im using a windows 8 64bit notebook*)

Any sugestions???

**Comment by DougBrazil** [comment]
Have also tried changing clash of clans languague to english and the problem remains

**Comment by DougBrazil** [comment]
Do i need to download the source code for anything? Im just using the .jar file

**Comment by norecha** [comment]
No, jar is enough.
StateIdle is 99% resolution related, put a screenshot here let me see

**Comment by sitolawrence** [comment]
I have the same issue...when i allow pokubot to adjust resolution for me it adjusts so that the game doesn't fit in my windows. I kind of got around that (it's still a pain though) but now it's stateidle always popping up

**Comment by norecha** [comment]
How did you get around that exactly?
bot wont work if your resolution is wrong. google how to change bs resolution manually from registry

**Comment by sitolawrence** [comment]
I didn't fit so I just tried my best to adjust but...what is the ideal resolution it needs to be?

**Comment by norecha** [comment]
read instructions

**Comment by sitolawrence** [comment]
Thank you!

**Comment by DougBrazil** [comment]
I found a registry editor that came with another bot (the bytecode club)... That automatic worked! ;)

Im testing your bot now, sometimes after a few searches it disconects and reconects, but its working

Enviado do meu iPhone

**Comment by DougBrazil** [comment]
Look for the registry editor on the coc bot that is on the bytecode club... His editor works automatically... Restart the pc and its now working

Enviado do meu iPhone
