### ISSUE TITLE
Barrack Boost Bug, Screenshot :)

### ISSUE THREAD

**Issue by dennyle0103** [norecha/pokubot#40]
![capture](https://cloud.githubusercontent.com/assets/11020367/6315793/b3d33edc-b9c2-11e4-8d06-ac7a836519c2.PNG)

**Comment by norecha** [comment]
Boost other barracks, not first one for now

**Comment by norecha** [comment]
Actually I have a fix for it, even if you boost first rax, write your email, I can send you the new version to test

**Comment by dennyle0103** [comment]
dogpoundapb@gmail.com

**Comment by sheep313** [comment]
Hi Norecha,

Love your work but no matter what I do, how many times I reset my settings I can't get poku working even with 2nd - 4th barracks boosted only.

Has worked fine prior to this without any boosts.

Could you email me the test version also? :)

**Comment by sheep313** [comment]
Just wanted to add that I also boosted both heroes, not sure if that's what is causing the issue as I haven't tested that yet.

**Comment by norecha** [comment]
What is your email

**Comment by sheep313** [comment]
be4747e8@opayq.com okay or do you need a gmail address? :)

Thanks in advance!

**Comment by sheep313** [comment]
@norecha 
Working flawlessly champ, not sure why I couldn't get 1.0.2 working, I troubleshot the shit out of it but couldn't get it going even though other people are using it without any problems.

Hit me up via email if you need anymore guinea pigs in future <3

Keep up the great work champ :)

**Comment by charles9823** [comment]
pls send me the other verson i cant boost my barrack because when i boost it wont work for m e
cnzk9823@gmail.com

**Comment by norecha** [comment]
I made a new release with that version. Use 1.0.3

**Comment by curtisrami** [comment]
ramadani.kujtim@hotmail.com thank you :)
