### ISSUE TITLE
The bot stops before attacking

### ISSUE THREAD

**Issue by ZiadYasser** [norecha/pokubot#57]
First of all Thanks for the amazing bot. I really appreciate your effort.
I have this small problem that however the amount I put in the bot it never attack or continue searching. Every time it tells me sleep interrupted and runner is failed.
So if you please can help me i will appreciate it. 

![untitled](https://cloud.githubusercontent.com/assets/11733820/6915140/f7b4c3ae-d791-11e4-8930-33aeacb1cbcc.png)

**Comment by ZiadYasser** [comment]
And with version 1.0.3 I have this problem 

![untitled1](https://cloud.githubusercontent.com/assets/11733820/6915697/82b30ed0-d796-11e4-92cb-a2276cd0872e.png)

**Comment by gabbiano** [comment]
after the latest update of the game if you get disconnected for qalsiasi problem poku not only restart but you have to give a new start, or after giving the stop you know the why?
