### ISSUE TITLE
How to fix the "Barracks location is not correct." 

### ISSUE THREAD

**Issue by Obitoy** [norecha/pokubot#58]
![error](https://cloud.githubusercontent.com/assets/11912546/7106286/0d59b8be-e16e-11e4-9310-a5d038cd0d32.png)

**Comment by lem77** [comment]
I have the same problem anybody can help thanks

**Comment by jarredhawkins** [comment]
https://github.com/norecha/pokubot/commit/a2ca42947072159fc10ef7d639ebe8be50d3b699

Try reconfiguring as posted there.

If that doesn't work, ensure your resolution is set up properly. It may require a restart of your computer to get the resolution working properly.

**Comment by junaid9900** [comment]
Hack

**Comment by junaid9900** [comment]
I have the some problem anybody can help
