### ISSUE TITLE
new update clash of clans

### ISSUE THREAD

**Issue by criss5200** [norecha/pokubot#59]
I would like to know if pokubot will update to a new version because with the last update of clash of clans pokubot not works (sorry for my english but i'm italian)

**Comment by norecha** [comment]
What exactly is broken?

**Comment by criss5200** [comment]
when pokubot attack it stays on the same village and it doesn't change

**Comment by norecha** [comment]
Nothing should be changed with that, it works fine for me and other 
people. Game is in English right?
