### ISSUE TITLE
StateIdle despite manually changing resolution

### ISSUE THREAD

**Issue by fsa259** [norecha/pokubot#64]
Oh glorious creator of PokuBot,

As per your FAQs, I have manually changed the window h&w to what you recommended, but still getting StateIdle....what else should I be looking at fixing?

**Comment by fsa259** [comment]
http://s10.postimg.org/6fol9igu1/Untitled.png

**Comment by norecha** [comment]
Does it zoom out when it says its zooming out?
If not, just restart your BS and run bot again, or just restart your pc

**Comment by nayrb05** [comment]
hi im also had a problm with pokubot its always in stateidle
