### ISSUE TITLE
Zoom Up can be optimized

### ISSUE THREAD

**Issue by bhysyq** [norecha/pokubot#65]
Hi @norecha ,

I think the Zoom Up function can be optimized by pressing `Ctrl` and `-`. Do you want me make a pull request for that?

Thanks,

bhysyq

**Comment by norecha** [comment]
I had a bad luck with Ctrl button, if user happens to click it at the same time, it can be messy. Besides zoom out is not really a bottleneck. We need to wait for army anyway, it is not making it any slower. Only when you find a target to attack, it slows you down like 10 sec, and considering it is every ~30 min, I say it is fine.
