### ISSUE TITLE
attack or deploy button for manual mode

### ISSUE THREAD

**Issue by larknart** [norecha/pokubot#7]
maybe can add some button for easy half manual mode player.. something like this attachment
![atckbtn](https://cloud.githubusercontent.com/assets/2086142/5916083/fda180ca-a647-11e4-9411-9d5ac8d3dca7.jpg)

**Comment by norecha** [comment]
If you are going to use it manually, dropping troops manually will always be better than bot's dropping them. I assume you want this to make sure base is good to attack but again you can just drop it yourself for better results. I will still try to implement this but right now it will be lower priority
