### ISSUE TITLE
Number Parsing problem

### ISSUE THREAD

**Issue by bjwhite3114** [norecha/pokubot#73]
As you requested in other post, I just saw a number parsing error on my first auto-selected / searched attack.   I had it set to   170000 / 170000 / 700 for search criteria  and it attacked someone with the following:

70 738  Gold
125 505  Elixer
975   DE

Hope this helps!

**Comment by norecha** [comment]
Are you sure you had match all conditions selected?

**Comment by bjwhite3114** [comment]
Well shoot.  yes you are correct!   Got it running again so I'll let you know.
