### ISSUE TITLE
StateIdle

### ISSUE THREAD

**Issue by rollbacks** [norecha/pokubot#8]
Hello dear norecha, i tried to get the bot work..but nothing happend.
I got this message every time im trying to start the bot:
[01.26.15 1:00:38 PM] INFO: StateIdle
[01.26.15 1:00:39 PM] INFO: StateIdle
[01.26.15 1:00:40 PM] INFO: StateIdle
[01.26.15 1:00:42 PM] INFO: StateIdle
[01.26.15 1:00:43 PM] INFO: StateIdle
[01.26.15 1:00:44 PM] INFO: StateIdle

What i tried to do:
Replace serevel versions of Bluestacks,tried also Offline installer of bluestacks,Tried rooted bluestacks.
Deleted java and reinstall it [ java 8 ] 
Delete antivirus/bot folder on %appdata% and re configure it.
restart bluestacks//restart computer..
but nothing works :/ Windows 7 64Bit hope you can help me out.

**Comment by norecha** [comment]
It probably means it cannot detect your attack button on bottom left. I'm also on w7 64 bit so it shouldn't be any problem.
Only reason I can think of is your resolution is not correct. Or your color values are really different from what I tested it. If you are willing to help me debug it, lmk, I will send you some tools

**Comment by rollbacks** [comment]
Hey norecha,yes i want to help you try debug it..send me the tools you need
here my email:
amdking91@walla.com

btw,on what the res you using on the computer?

**Comment by norecha** [comment]
He said the reason for this was antivirus blocking bot's clicks. it is fixed now

**Comment by flyleaf61** [comment]
i had same problem ,  how can i fix this   "INFO: StateIdle" , please help me .  My OS is w7 32bit
