### ISSUE TITLE
pokubot not working at new version of COC

### ISSUE THREAD

**Issue by mike0419** [norecha/pokubot#89]

**Comment by hugh1li** [comment]
Yeah, I found not working now... Waiting for Norecha

**Comment by 1-Click-Dev** [comment]
waiting and supporting him!

**Comment by norecha** [comment]
I'm really busy these days and won't have time to update it for some time. If anyone else wants to fix it, I will be happy to merge it

**Comment by mike0419** [comment]
that's all right, we will be patient and wait ...

**Comment by gabbiano** [comment]
if you start the search he just continues , not only manages to zoom in and click on the button panoramic army

**Comment by norecha** [comment]
I will release a new version today

**Comment by frpedraya88** [comment]
hi @norecha sir, what time can you post the new update of the bot? thanks :+1:

**Comment by norecha** [comment]
it is released

**Comment by marvie** [comment]
Norecha i'm having status idle problem....any suggestions?? My other laptop is fine with it...it's just mu dell inspiron whose having problems

**Comment by norecha** [comment]
Is it stuck at "find a match" view?

**Comment by marvie** [comment]
no just idle it doesn't detect d game i think

**Comment by mike0419** [comment]
I encountered the "find match" issue as descripted above, pokubot worked well at first few hours then issue happened

**Comment by norecha** [comment]
I realized when you have a shield, that button moves little bit. I'm 
fixing it now

**Comment by datdot** [comment]
Why it doesn't drop CC?
